Update rate reminder documentation
nstack-io/documentation pull request #19
Opened 2019-10-11 15:34 UTC by alex199568

2019-10-15 11:12 UTC, markusrubey commented
Looking good, just one minor thing I noticed is that sometimes we say `nstack` and sometimes `NStack`, think the latter one is correct. Also `sdk` could be `SDK`

2019-10-15 11:13 UTC, msmoljan requested changes

2019-10-15 11:13 UTC, msmoljan commented on docs/guides/Android/Android-Rate-Reminder.md
> +`./gralew generateRateReminderActions` will create `RateReminderActions` with methods which send events to nstack backend. App should call those methods when an event happens.
./gra_d_lew

2019-10-16 03:56 UTC, merged

2019-10-16 04:00 UTC, Casperhr commented
can you just double check all is in